# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_RSPMatrix_rcpp_hello_world`)
}

SetSequential <- function() {
    invisible(.Call(`_RSPMatrix_SetSequential`))
}

SetMulticore <- function() {
    invisible(.Call(`_RSPMatrix_SetMulticore`))
}

SetGPU <- function() {
    invisible(.Call(`_RSPMatrix_SetGPU`))
}

SPMatrix <- function(rows, columns) {
    .Call(`_RSPMatrix_SPMatrix`, rows, columns)
}

FillSPMatrix <- function(m) {
    invisible(.Call(`_RSPMatrix_FillSPMatrix`, m))
}

SPMultiplication <- function(a, b) {
    invisible(.Call(`_RSPMatrix_SPMultiplication`, a, b))
}

SPAddition <- function(a, b) {
    invisible(.Call(`_RSPMatrix_SPAddition`, a, b))
}

PrintSPMatrix <- function(m) {
    invisible(.Call(`_RSPMatrix_PrintSPMatrix`, m))
}

